wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.6
    framework: huggingface
    huggingface_version: 4.25.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1671479199.899526
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 63
      - 74
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 63
      - 74
      3:
      - 1
      - 2
      - 16
      - 17
      - 23
      - 37
      4: 3.7.11
      5: 0.13.6
      6: 4.25.1
      8:
      - 5
      10:
      - 3
batch_size:
  desc: null
  value: 16
clip_grad:
  desc: null
  value: 3.0
dataset:
  desc: null
  value:
    MIM:
      pred_aspect_ratio: (0.3, 1/0.3)
      pred_ratio: 0.3
      pred_ratio_var: 0.0
      pred_shape: block
      pred_start_epoch: 50
    augmentations:
      global_crops_number: 2
      global_crops_scale: (0.7, 1.)
      local_crops_number: 12
      local_crops_scale: (0.05, 0.4)
    loader:
      drop_last: true
      num_workers: 75
      pin_memory: true
    train_path: /raid/fabian/ssl-data/
    val_loader:
      drop_last: true
      num_workers: 75
      pin_memory: true
      shuffle: false
    val_path: /raid/fabian/downstream/fitzpatrick17k/
decryption:
  desc: null
  value:
    keys: null
downstream:
  desc: null
  value:
    fitz_path: null
    ham_path: null
    isic_path: null
    lr: 0.001
    pu_path: null
    splitter:
      num_workers: 75
      val_size: 0.3
downstream_every_n_epochs:
  desc: null
  value: 100
downstream_train_epochs:
  desc: null
  value: 10
embed_vis_every_n_epochs:
  desc: null
  value: 20
epochs:
  desc: null
  value: 100
fine_tune_from:
  desc: null
  value: None
imgs_to_visualize:
  desc: null
  value: 5
loss:
  desc: null
  value:
    lambda1: 1.0
    lambda2: 1.0
    teacher_patch_temp: 0.07
    teacher_temp: 0.04
    warmup_teacher_patch_temp: 0.04
    warmup_teacher_temp: 0.04
    warmup_teacher_temp_epochs: 30
lr:
  desc: null
  value: 0.005
min_lr:
  desc: null
  value: 5e-4
model:
  desc: null
  value:
    base_model: swin_tiny
    emb_dim: 384
    eval:
      avgpool_patchtokens: false
      n_last_blocks: 4
    model_type: VIT
    norm_last_layer: true
    out_dim: 4096
    patch_out_dim: 4096
    shared_head: true
    shared_head_teacher: true
    student:
      drop_path_rate: 0.1
      masked_im_modeling: true
      patch_size: 4
      return_all_tokens: true
      window_size: 7
    teacher:
      drop_path_rate: 0.0
      patch_size: 4
      return_all_tokens: true
      window_size: 7
    use_bn_in_head: false
momentum_teacher:
  desc: null
  value: 0.996
optim:
  desc: null
  value: adamw
optimizer:
  desc: null
  value:
    freeze_last_layer: 1
save_every_n_epochs:
  desc: null
  value: 10
seed:
  desc: null
  value: 42
use_lr_scheduler:
  desc: null
  value: true
use_wd_scheduler:
  desc: null
  value: true
visualize_attention:
  desc: null
  value: true
warmup_epochs:
  desc: null
  value: 10
weight_decay:
  desc: null
  value: 0.04
weight_decay_end:
  desc: null
  value: 0.4
